"""Add cascade delete

Revision ID: 8a7ad56b6773
Revises: 886da2358aec
Create Date: 2025-11-03 20:49:57.286089

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a7ad56b6773"
down_revision: Union[str, Sequence[str], None] = "886da2358aec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("books_author_id_fkey"), "books", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "books", "authors", ["author_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "books", type_="foreignkey")
    op.create_foreign_key(
        op.f("books_author_id_fkey"), "books", "authors", ["author_id"], ["id"]
    )
    # ### end Alembic commands ###
